name: Deploy CI

on:
  workflow_run:
    workflows: Vue.js CI
    branches: master
    types: completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "dist/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        EXCLUDE: "/dist/, /node_modules/"